packages:
  - "apps/*"
  - "backend/*"
  - "packages/*"

allowBuilds:
  "@nestjs/core": true
  msgpackr-extract: true
  sharp: true
  unrs-resolver: true

onlyBuiltDependencies:
  - sharp
  - unrs-resolver
  - "@nestjs/core"
  - msgpackr-extract
